### ISSUE TITLE
LYWSD03MMC does not refresh data after some time

### ISSUE THREAD

**Issue by damszew** [tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#12]
Hi, 

I have a problem when using this add-on with `LYWSD03MMC`. After some time gateway stops refreshing data from this devices.

My current setup is: 2 `LYWSD03MMC` sensors and some weather addon. Logs from my gateway when this happens: https://pastebin.com/7R00cBNp

Most interesting part is around `2020-12-16 15:10:21.073` after which three are no "Reading ..." logs up until I remove and add devices again.

Related to #5 and #8

**Comment by damszew** [comment]
Seems to be related to https://github.com/abandonware/noble/pull/141 which is **merged** but not yet available in any release

**Comment by tim-hellhake** [comment]
> Seems to be related to abandonware/noble#141 which is merged but not yet available in any release

Well then let's try the latest version :)
I'll prepare an update.

**Comment by damszew** [comment]
Thanks, I'll update my gateway and test it for few days

**Comment by damszew** [comment]
It seems that new version of add-on fixes my issue. Thank you very much!

I have exactly the same set-up as before - sensors in same places, same devices added to gateway, etc. and I haven't seen any problems with readings from any of my `LYWSD03MMC`.
