### ISSUE TITLE
Pairing XIAOMI Mijia Bluetooth Thermometer 2 fails

### ISSUE THREAD

**Issue by jfrohn** [tim-hellhake/xiaomi-temperature-humidity-sensor-adapter#5]
I tried to add the new XIAOMI Mijia Bluetooth Thermometer 2 (model number LYWSD03MMC). The device was quickly detected but does not show any temperature or humidity readings. In the logs I can find, that the pairing failed:

>2019-12-21 11:14:52.564 INFO   : Loading add-on: xiaomi-temperature-humidity-sensor-adapter
>2019-12-21 11:14:53.352 INFO   : xiaomi-temperature-humidity-sensor: Opening database: /home/pi/.mozilla-iot/config/db.sqlite3
2019-12-21 11:14:54.025 INFO   : xiaomi-temperature-humidity-sensor: Loading add-on xiaomi-temperature-humidity-sensor-adapter from /home/pi/.mozilla-iot/addons/xiaomi-temperature-humidity-sensor-adapter
2019-12-21 11:14:54.286 INFO   : xiaomi-temperature-humidity-sensor: Noble adapter is poweredOn
2019-12-21 11:14:54.288 INFO   : xiaomi-temperature-humidity-sensor: Start scanning for devices
2019-12-21 11:14:55.066 INFO   : xiaomi-temperature-humidity-sensor: Detected new Temperature Humidity Sensor with id a4c13844063f
2019-12-21 11:15:05.766 INFO   : About to call startPairing on ThingURLAdapter
2019-12-21 11:15:05.768 INFO   : About to call startPairing on TemperatureHumiditySensorAdapter
2019-12-21 11:15:05.866 INFO   : xiaomi-temperature-humidity-sensor: Adapter: TemperatureHumiditySensorAdapter id TemperatureHumiditySensorAdapter pairing started
2019-12-21 11:15:05.872 INFO   : Opened a new things socket
2019-12-21 11:15:16.858 INFO   : Successfully created new thing Temperatur Sensor
2019-12-21 11:15:19.418 ERROR  : Thing was not added
2019-12-21 11:15:19.419 ERROR  : addNewThing cancelled
2019-12-21 11:15:19.428 INFO   : thing-url: Adapter: ThingURLAdapter id thing-url-adapter pairing cancelled
2019-12-21 11:15:19.429 INFO   : xiaomi-temperature-humidity-sensor: Adapter: TemperatureHumiditySensorAdapter id TemperatureHumiditySensorAdapter pairing cancelled

I can see that your plugin successfully detected the new device. Still adding the thing in the gateway failed. Do you see any possible errors?
Also, once the thing is added it cannot be removed anymore. This seems to be a problem with the gateway though.

Thanks!

**Comment by tim-hellhake** [comment]
> I can see that your plugin successfully detected the new device. Still adding the thing in the gateway failed.

How did it fail?
Did the gateway show you a new device when you opened the `add things` dialog?
If so, what happened when you clicked on the `save` button?

> Do you see any possible errors?

The messages `ERROR : Thing was not added` and `ERROR : Thing was not added` just indicate that you clicked on the `Cancel` button of the `add things` dialog.
The last message from the adapter is `Detected new Temperature Humidity Sensor with id a4c13844063f`.
This means that a new device was created which should now be visible in the `add things` dialog.

> Also, once the thing is added it cannot be removed anymore. This seems to be a problem with the gateway though.

Yes this is a known problem of the gateway.
Restarting the gateway helped me most of the time.

Can you please try to add the device again after restarting the adapter?

**Comment by jfrohn** [comment]
> Did the gateway show you a new device when you opened the add things dialog?
If so, what happened when you clicked on the save button?

Yes, the gateway shows the device immediately when I opened the add things dialog. I can also add it without a problem and the sensor is shown as a thing after I click save. The problem is that it shows no values for the temperature and the humidity afterwards. The event log for the thing is also empty.

I did not click on cancel or interrupt the pairing in any other way. The logs are taken directly from the installation process. As you can see from the timestamps this happens immediately after the thing is added.

>Yes this is a known problem of the gateway.
Restarting the gateway helped me most of the time.

I restarted the pi but it didn't help. For now I just deleted the db and readded the plugin. Afterwards adding the sensor again led to the same problem. I have latest version of webthings 0.10.0 and just upgraded the pi.

**Comment by tim-hellhake** [comment]
> The problem is that it shows no values for the temperature and the humidity afterwards.

That's normal.
The sensor broadcasts its data in multiple packets at regular intervals.
Until the first packets arrive the values are zero.
They should change after a few minutes.

> I restarted the pi but it didn't help. For now I just deleted the db and readded the plugin. Afterwards adding the sensor again led to the same problem. I have latest version of webthings 0.10.0 and just upgraded the pi.

I usually test on the latest master.
Maybe the issue is already fixed there.
I'll try to reproduce it on a fresh 0.10.0 gateway installation.

**Comment by faberto** [comment]
The sensor has changed its way to transmit the data. The package used by this add-on does not support the new way. Its outdated. I'm not aware of any JS implementation of the protocol.
https://github.com/JsBergbau/MiTemperature2/

**Comment by jfrohn** [comment]
Thank you @faberto! Also, since the sensor now needs to establish a bluetooth connection it will make it unusable for my purposes anyway.

I think this ticket can be closed then.

**Comment by dadall** [comment]
Hey there,

I've a Xiaomi Bluetooth Temperature and Humidity Sensor,  LYWSD03MMC. This issue seems to be the correct place to ask for some news about its support by this addon :)

Cheers,

**Comment by tim-hellhake** [comment]
@dadall The last update added support for it.
